services:
  valkey:
    image: valkey/valkey
    ports:
      - 6379:6379
  qdrant:
    image: qdrant/qdrant
    ports:
      - 6333:6333
  db:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: tiger
      POSTGRES_DB: testdb
  admin:
    image: adminer
    restart: always
    depends_on: 
      - db
    ports:
      - 8080:8080