import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import {
  ClerkProvider,
  SignUp,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider> {/* Wrap your entire application with ClerkProvider */}
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Content displayed when the user is signed out */}
        <SignedOut>
          {/* This section could be a dedicated sign-in/sign-up page */}
          <section className="bg-gray-100 min-h-screen flex items-center justify-center">
            <SignUp />
          </section>
        </SignedOut>

        {/* Content displayed when the user is signed in */}
        <SignedIn>
          {/* Main application layout for signed-in users */}
          <div className="flex flex-col min-h-screen"> {/* Use flex column for layout */}
            {/* Header with UserButton */}
            <header className="w-full p-4 bg-white shadow flex justify-between items-center">
              {/* You can add your app logo or title here */}
              <span className="text-xl font-bold">My App</span>
              <UserButton/> {/* User button, redirects to home after sign out */}
            </header>

            {/* Main content area */}
            <main className="flex-grow p-4"> {/* flex-grow makes main take up available space */}
              {children} {/* This is where your page content will render */}
            </main>

            {/* Optional: Footer */}
            {/* <footer className="w-full p-4 bg-gray-200 text-center">© 2023 My App</footer> */}
          </div>
        </SignedIn>
      </body>
    </html>
  </ClerkProvider>
  );
}
